# Site
repository: mortezza/
# favicon: images/favicon.ico

# Personal info
name: Morteza Saki
title: Information Security Expert
email: mortezasaki91[at]gmail[dot]com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  mortezza
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: morteza_sa__
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/3x4.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Morteza and I'm a information security expert. As well as researcher I also have experience making software and web apps. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>Programming</mark> , <mark>Pentesting</mark> , <mark>Web Crawilng</mark> , <mark>Automation</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Bodybuilding
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: mortezza

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
